### ISSUE TITLE
--help doesn't work

### ISSUE THREAD

**Issue by mauke** [rjbs/Dist-Zilla#175]
`dzil release --help` doesn't display help for the release command. It doesn't complain about an invalid option either. It ignores the option and blindly tries to release the module. :-(

**Comment by ambs** [comment]
This seems likely to be fixed?

````
$ dzil release --help
dzil release [long options...]

	--trial   build a trial release that PAUSE will not index
`````

**Comment by jonasbn** [comment]
Made the same observation as @ambs, @mauke what is the behaviour you expect? @rjbs what is would be the expected behaviour or ambition level for output? some of the other `--help` variants are more explicit - it is #hacktober and this looks like a good candidate

**Comment by karenetheridge** [comment]
The current output is correct. There are no other options to document. I think this issue can be closed.

**Comment by ambs** [comment]
But we need someone with that power :-)
