### ISSUE TITLE
`dzil help` doesn't show dzil usage help; `dzil commands` does

### ISSUE THREAD

**Issue by mauke** [rjbs/Dist-Zilla#177]
`dzil commands` displays dzil usage information:

    dzil <command> [-Iv] [long options...]
            -v --verbose      log additional output
            -I --lib-inc      additional @INC dirs

... followed by the list of available commands.

`dzil help` only shows the list of available commands.

I think this is backwards.

**Comment by rjbs** [comment]
I think this is fixed by using a new GLD.  Should be confirmed.

**Comment by rjbs** [comment]
@dha confirms this is sorted!
