### ISSUE TITLE
options taking arguments not listed as such in help

### ISSUE THREAD

**Issue by mauke** [rjbs/Dist-Zilla#181]
See e.g. `dzil help add`:

    dzil [-Pp] [long options...] <ModuleName>
    
            -p --profile      name of the profile to use
            -P --provider     name of the profile provider to use

It doesn't say where to put the names of the profile or the provider.

Similarly, `dzil help build`:

    dzil build [long options...]
    
            --trial    build a trial release that PAUSE will not index
            --tgz      build a tarball (default behavior)
            --in       the directory in which to build the distribution

Presumably `--in` takes an argument and the other two options don't but that's not clear from the listing.

**Comment by rjbs** [comment]
I think this may be fixed by using a new Getopt::Longe:Descriptive.  Needs confirmation.

**Comment by rjbs** [comment]
Confirmed.  Example:

```
~/code/cs/Dist-Zilla$ dzil help new
dzil [-Pp] [long options...] <ModuleName>

        -p STR --profile STR     name of the profile to use
        -P STR --provider STR    name of the profile provider to use

~/code/cs/Dist-Zilla$ dzil help build
dzil build [long options...]

This command is a very thin layer over the Dist::Zilla "build" method, which
does all the things required to build your distribution. By default, it will
also archive your distribution and leave you with a complete,
ready-to-release distribution tarball.

        --trial   build a trial release that PAUSE will not index
        --tgz     build a tarball (default behavior)
        --in STR  the directory in which to build the distribution
```
