### ISSUE TITLE
Make log warnings go to STDERR

### ISSUE THREAD

**Issue by hoelzro** [rjbs/Dist-Zilla#184]
Hi there,

I think I reported this in RT a while ago, but I can't seem to find it, so I think it may have been lost in the move to GitHub issues.

It would be nice if log warnings went to standard error.  I run `dzil listdeps --missing` on one of my repositories and see this on standard output:

    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Link/InterWiki.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Paragraph.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Bold.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Deleted.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/ListItem.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Link/WindowsShare.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Underlined.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Heading.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/EmailAddress.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Subscript.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Link.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/NoTOC.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Link/External.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Superscript.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Role/Parser/CamelCaseLinks.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Footnote.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Italic.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Link.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Image.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Link/Internal.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/List.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Monospace.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Document.pm
    [@Default/Name] couldn't find abstract in lib/Text/DokuWiki/Element/Text.pm
    Test::HTML::Differences

I often do something like `dzil listdeps --missing | xargs cpanm`, and this really messes cpanm up.

Thanks,
Rob

**Comment by karenetheridge** [comment]
This should be easy enough to do with some Log::Dispatchouli config fiddling?

**Comment by rjbs** [comment]
This isn't really trivial, since we don't distinguish between warnings and anything else.

This really shouldn't happen, though.  The chrome is muted before listdeps does any work.  I couldn't reproduce the problem, either.  In general, in commands like this one, we mute the chrome.
