### ISSUE TITLE
MetaNoIndex namespace excludes the package itself

### ISSUE THREAD

**Issue by stevenl** [rjbs/Dist-Zilla#204]
According to the documentation for the `namespaces` attribute in MetaNoIndex:

> NOTE: This will not exclude the package My::Package, only everything under it like My::Package::Foo.

However, My::Package is in fact excluded with the following configuration:

    [MetaProvides::Package]
    inherit_version = 1
    meta_noindex    = 1

    [MetaNoIndex]
    namespaces = My::Package

**Comment by rjbs** [comment]
This is probably a bug in MetaProvides, I think.  All that MetaNoIndex does is add the namespace to the no_index metadata.  The metadata spec says: namespace = A List of package namespaces, where anything below the namespace must be ignored, but not the namespace itself.

So, if MetaProvides::Package is ignoring this namespace, that's the bug.
