### ISSUE TITLE
PodVersion plugin breaks if NAME is more than one line.

### ISSUE THREAD

**Issue by lucastheisen** [rjbs/Dist-Zilla#205]
In [perlpodstyle] [1], it says:

> The description should ideally fit on a single line, even if a man program replaces  the dash with a few tabs

The words *should ideally* lead me to believe that it could be 2 lines.  If it is, the plugin will fail.  A very simple fix would be to change line 23:

    $_++; # move past the line with the abstract

to this:

    $_++ while ( $content[$_] !~ /^\s*$/ ); # move past the abstract

As this is my first module, it is just as likely that this is desired behavior but the perlpodstyle seems to leave the door open and it would be simple to support multi-line abstracts...  Anyway, I modified my module to be one line but figured I would submit the bug anyway.

  [1]: http://perldoc.perl.org/perlpodstyle.html#DESCRIPTION "perlpodstyle"

**Comment by rjbs** [comment]
I think this was already fixed, and should be confirmed.

**Comment by rjbs** [comment]
@dha said tested and okay!
