### ISSUE TITLE
optional specify versions in listdeps

### ISSUE THREAD

**Issue by xenoterracide** [rjbs/Dist-Zilla#262]
related to https://github.com/SineSwiper/Dist-Zilla-TravisCI/issues/14

if listdeps could output the versions required when specified that would fix this problem. 

    [Prereqs]
    Locale::Currency = 3

then `listdeps --with-versions` could output

     Locale::Currency~3

obviously this should be optional because I think only `cpanm` supports this syntax (could be wrong)

**Comment by rjbs** [comment]
`dzil listdeps --cpanm` exists as of e0a38ad!

**Comment by fgabolde** [comment]
Sorry for asking here but it's not working out of the box for me. I'm probably missing some subtlety of shell parameter handling:

    $ dzil listdeps --missing --cpanm
    Test::More~"== 1.001003"

And also:

    $ cpanm -v Test::More~"== 1.001003"
    cpanm (App::cpanminus) 1.7042 on perl 5.018004 built for x86_64-linux
    [snip]
    Written by John Gilmore and Jay Fenlason.
    You have /usr/bin/unzip
    Searching Test::More (== 1.001003) on cpanmetadb ...
    --> Working on Test::More
    Fetching http://backpan.perl.org/authors/id/E/EX/EXODIST/Test-Simple-1.001003.tar.gz ... OK
    [snip]

But:

    $ dzil listdeps --missing --cpanm | cpanm -v
    cpanm (App::cpanminus) 1.7042 on perl 5.018004 built for x86_64-linux
    [snip]
    Written by John Gilmore and Jay Fenlason.
    You have /usr/bin/unzip
    Searching Test::More~"== () on cpanmetadb ...
    ! Finding Test::More~"== on cpanmetadb failed.
    Searching Test::More~"== () on metacpan ...
    ! Could not find a release matching Test::More~"== () on MetaCPAN.
    [snip]

Also but:

    $ echo 'Test::More~"== 1.001003"' | cpanm -v
    [same as above]

This is Dist::Zilla 6.008 (latest at this time).

**Comment by karenetheridge** [comment]
@fgabolde you didn't link to the dist.ini that produces that cpanm output?  I don't think it's correct:

    : [ether@bourbon ~]$; cpanm -v Test::More~"== 1.001003"
    cpanm (App::cpanminus) 1.7042 on perl 5.025009 built for darwin-2level
    Work directory is /Users/ether/.cpanm/work/1487961286.9013
    You have make /usr/bin/make
    You have LWP 6.19
    You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
    You have /usr/bin/unzip
    Searching Test::More on mirror http://mirrors.gossamer-threads.com/CPAN ...
    Downloading index file http://mirrors.gossamer-threads.com/CPAN/modules/02packages.details.txt.gz ...
    Uncompressing index file...
    Can't convert '': Invalid version format (version required)

**Comment by fgabolde** [comment]
@karenetheridge That's weird... that's the same exact thing as my second example (down to the cpanm version) which works on my machine (as per the cpanm docs). I wonder why it doesn't work for you. Different versions of CPAN::Meta::Requirements maybe?

As for the dist.ini it's back at work where I won't be for the weekend, but it's basically

    Test::More = == 1.001003

I can check back here on Monday with the actual full dist.ini file.

**Comment by karenetheridge** [comment]
I think the 'invalid version format' error is a red herring -- something else is broken with some of my cpanm files.

**Comment by fgabolde** [comment]
Here is the `dist.ini` file.  The only change is the path to the repositories.

    name                    = Test-Requirements
    author                  = Fabrice Gabolde <fgabolde@weborama.com>
    license                 = None
    copyright_holder        = Weborama
    copyright_year          = 2015
    version                 = 0.003
    
    main_module             = lib/Test/RequiresModule.pm
    
    [GatherDir]
    [PruneCruft]
    [ManifestSkip]
    [MetaJSON]
    [ExecDir]
    [ShareDir]
    [PkgVersion]
    use_package             = 1
    [ModuleBuild]
    [MetaTests]
    [PodWeaver]
    [Manifest]
    
    [MetaResources]
    homepage                = http://example.com/test-requirements
    repository.url          = http://example.com/test-requirements.git
    repository.web          = http://example.com/test-requirements
    repository.type         = git
    
    [Prereqs]
    perl                    = 5.012
    Carp                    = 0
    autodie                 = 0
    base                    = 0
    Test::Builder::Module   = 0
    strict                  = 0
    utf8                    = 0
    warnings                = 0
    
    [Prereqs / Recommends]
    
    [Prereqs / TestRequires]
    Test::Builder::Tester   = 0
    Test::More              = == 1.001003

The current version of this has `Test::More              = <= 1.001014` which does not change a thing.

**Comment by akhuettel** [comment]
I've had a hard time getting this to work, but I suspect the bugs are on the side of App::cpanminus. Results from memory are:
1) dzil listdeps *can* be piped into cpanm, but then it doesnt provide minimal versions
2) dzil listdeps --cpan *cannot* be piped into cpanm, unclear why, but if you shove it in with xargs you can do it
3) dzil listdeps --cpan | xargs cpanm --skip-satisfied     *miscalculates* and ignores needed updates of already installed packages
4) dzil listdeps --missing | xargs cpanm    works...
So now in https://github.com/lab-measurement/lab-measurement/blob/master/.travis.yml I let DZ figure out what is missing, not cpanm, and then let cpanm install that unconditionally.

**Comment by dolmen** [comment]
Note that `dzil listdeps --json` can be piped through a JSON transformer (such as [jq](https://stedolan.github.io/jq/) if you need advanced filtering or fancy output.
