### ISSUE TITLE
Please add a safeguard against running `dzil build --in .` as it deletes all files including `dist.ini`

### ISSUE THREAD

**Issue by xtaran** [rjbs/Dist-Zilla#341]
For using http://coveralls.io/ I thought the easiest way to get a directory with a all files necessary for a build is to add the generated files to the current working directory. Of course I first tried it locally and because stuff is in git I didn't fear modified or deleted files. But to my surprise after running `dzil build --in .` my current directory was completely empty. No more `dist.ini`, no more `.git` directory.

So please add a safeguard against using the current directory together with `--in` to avoid unexpected data loss. (Or make it a special case to add/modify the files inline. But I guess that's way more complicated than to add a warning plus maybe a y/n question or to abort unless there's also a e.g. `--force` or `--yes-i-know-what-i-am-doing` option given, too.

**Comment by rjbs** [comment]
Forbidden by d3b6130.

**Comment by xtaran** [comment]
Yay, thanks!
