### ISSUE TITLE
Newline embedded in filename results in split filename in MANIFEST

### ISSUE THREAD

**Issue by neilb** [rjbs/Dist-Zilla#342]
I have a test file under t/.../ which has an embedded newline. Let's say the file is "Foo\nBar"

I excluded that in dist.ini with:

    [Encoding]
    encoding = bytes
    match = ^t/testpan/

But when I do `dzil build` I get a warning about two files not found in package.
This appears to be because Dist::Zilla::Plugin::MANIFEST doesn't escape the newline, so MANIFEST ends up with

    Foo
    Bar

**Comment by rjbs** [comment]
Fixed in 58a4b88.
