### ISSUE TITLE
Dist::Zilla 0.52 change for Makefile.PL/Build.PL can be interferred with by plugins

### ISSUE THREAD

**Issue by gozer** [rjbs/Dist-Zilla#367]
For instance, using [PerlTidy] in my dist.ini results in perltidy detecting these .PL files as perl files, and attempts to tidy them (i.e. indent them) **before** the templates are processed, resulting in a broken Makefile.PL...

**Comment by rjbs** [comment]
I agree that this is something the plugin must address.
