### ISSUE TITLE
Almost impossible to handle binary files by Dist::Zilla::File::OnDisk

### ISSUE THREAD

**Issue by stro** [rjbs/Dist-Zilla#399]
OnDisk.pm assumes encoding content based on Dist::Zilla::Role::MutableFile

If 'encoding' is not set, Dist::Zilla::Role::MutableFile->content tries to run Encode::decode and probably fails because of assuming UTF-8. 

If 'encoding' is set to 'bytes', then Dist::Zilla:::Role::File just dies in sub _decode because Dist::Zilla::Role::MutableFile->content tries to decode it anyway.

**Comment by rjbs** [comment]
Without further information, I'm closing this.  I'm guessing the real issue here is something trying to munge files it should not.
