### ISSUE TITLE
Please add a perltidyrc to the repo

### ISSUE THREAD

**Issue by autarch** [rjbs/Dist-Zilla#406]
It'd be great if you could add a tidy config file so I can easily tidy to match your style. Right now I have to do it all by hand when I work on PRs and that's quite tedious.

**Comment by karenetheridge** [comment]
I use this vim modeline for rjbs dists:

# vi:et:sts=2:sw=2:ts=2

**Comment by autarch** [comment]
I'm sure I could translate that into emacs, but a perltidy'd be better. @rjbs's code seems to be pretty consistently formatted, so I imagine he has a config he's already using.

**Comment by rjbs** [comment]
I have a config that emulates the formatting which I do consistently by hand.  I run perltidy only on *very* rare instances, generally when taking over a codebase someone else wrote that is a total mess.

But I've added it now.  I suggest you use it only on new code.  Sometimes I fiddle. ;)
