### ISSUE TITLE
:TestFiles returns all files under the t/ directory, not only *.t files run by prove

### ISSUE THREAD

**Issue by choroba** [rjbs/Dist-Zilla#407]
This leads e.g. to a release test error for [Net::HTTP::Spore](http://p3rl.org/Net::HTTP::Spore) which contains `t/specs/content.tgz` - but it makes no sense to test a binary file for tabs.

**Comment by choroba** [comment]
See `_setup_default_plugins`  in `Dist::Zilla::Dist::Builder`:

    sub { local $_ = $_->name; m{\At/} }

Should probably rather be

    sub { local $_ = $_->name; m{\At/.*\.t\Z} }

**Comment by karenetheridge** [comment]
We actually do want :TestFiles to return all t/ files - e.g. AutoPrereqs uses this to find all test prereqs.

To mark a file as binary/unscannable by plugins, set its encoding to 'bytes' in dist.ini -- see the docs for Dist::Zilla::Plugin::Encoding.

**Comment by choroba** [comment]
Ah, thanks. What about TSV files or shell scripts with `<<-HERE` documents? Is `bytes` still appropriate, or should one rather use a custom file gatherer?

**Comment by karenetheridge** [comment]
> Ah, thanks. What about TSV files or shell scripts with <<-HERE documents? Is bytes still appropriate, or should one rather use a custom file gatherer?

It all depends on what you want to achieve. Some things may still want to look at files in t/ that aren't perl code.

> But the (no tabs) test still fails:

Then you're in the wrong issue queue. But never fear, the maintainer has just uploaded a fix: https://metacpan.org/release/Dist-Zilla-Plugin-Test-NoTabs

**Comment by choroba** [comment]
Thanks :-)

**Comment by dolmen** [comment]
@choroba For the specific case of Net::HTTP::Spore, another solution would be to use a custom finder.
DZP::Test::NoTabs [uses the `FileFinderUser` role](https://metacpan.org/source/ETHER/Dist-Zilla-Plugin-Test-NoTabs-0.10/lib/Dist/Zilla/Plugin/Test/NoTabs.pm#L18), so you can override from dist.ini the default finders list that contains `[ ':InstallModules', ':ExecFiles', ':TestFiles' ]`.

You could try something like that in the dist.ini:

```
; Build a finder that inherits from :TestFiles but keeps only *.t
[FileFinder::Filter / TestCodeFiles]
finder = :TestFiles
skip = [^.][^t]$

[NoTabs]
finder = :InstallModules
finder = :ExecFiles
finder = :TestCodeFiles
```
