### ISSUE TITLE
deal with multiple CPAN accounts

### ISSUE THREAD

**Issue by garfieldnate** [rjbs/Dist-Zilla#412]
I have to comment and uncomment different CPAN credentials in config.ini so that I can release on personal and work accounts. Sometimes I forget to make the manual switch, and then I release a module on the wrong account, which is very annoying. It would help to be able to specify multiple accounts separately in the `.dzil` directory or within the `config.ini` file, and then choose which to release with using an argument to the `UploadToCpan` plugin or to the `dzil release` command.

Another thing that would help is if ConfirmRelease also stated the name of the CPAN account that is going to be released to.

**Comment by dolmen** [comment]
You could instead write an alternative [Role::Releaser](https://metacpan.org/pod/Dist::Zilla::Role::Releaser) module that would do exactly what you want. The [UploadToCPAN plugin](https://metacpan.org/pod/Dist::Zilla::Plugin::UploadToCPAN) is already bloated.

**Comment by garfieldnate** [comment]
Alright, I will think about that. I do notice an undocumented attribute in UploadToCPAN which would do what I asked for: `credentials_stash`. I think I could set it to `%PAUSE/WORK` in a dist.ini and then it would grab the credentials under that header in `config.ini`. Since there's no documentation, I don't know if that is meant to be public, but it seems useful.

However, now I see that what I want goes beyond that; %USER, %RIGHT, and %PAUSE need to be grouped together as a profile so I can say "work" and my work name, copyright, and pause info will get used. This info is needed by more than just UploadToCPAN, but also by other plugins that write pod. Just need to figure out how to edit the stash holding these values, or to intercept insertions.

**Comment by rjbs** [comment]
I've documented credentials_stash in 35dfc23.  I hope this helps!
