### ISSUE TITLE
Allow `dzil test` to pass command-line arguments to `Makefile.PL`

### ISSUE THREAD

**Issue by nwellnhof** [rjbs/Dist-Zilla#413]
I'd find it incredibly useful if `dzil test` had an option to pass command-line arguments to `Makefile.PL`. OTOH, I'm already using the `MakeMaker::Awesome` plugin so maybe this would be a better place for this feature.

**Comment by karenetheridge** [comment]
what sort of arguments did you have in mind?

**Comment by nwellnhof** [comment]
I specifically need `LIBS` and `INC`.

**Comment by Leont** [comment]
This sounds rather niche to me. PERL_MM_OPT is your friend, really.

**Comment by nwellnhof** [comment]
OK, closing the issue. If anyone's interested, here's a hack that makes `PERL_MM_OPT` work with `Devel::CheckLib`:

```
{
    local @ARGV;
    unshift(@ARGV, ExtUtils::MakeMaker::_shellwords($ENV{PERL_MM_OPT} || ''))
        if $ExtUtils::MakeMaker::VERSION >= 6.73_08;
    check_lib(...);
}
```

**Comment by karenetheridge** [comment]
That sounds like something that could be patched in Devel::CheckLib itself,
perhaps?

**Comment by nwellnhof** [comment]
Yes, I opened a ticket: https://rt.cpan.org/Ticket/Display.html?id=107109

**Comment by mattn** [comment]
Devel::CheckLib handle INC and LIBS. https://github.com/mattn/p5-Devel-CheckLib/blob/master/lib/Devel/CheckLib.pm#L196-L205
Do you mean it should be better to handle PERL_MM_OPT also?

**Comment by mattn** [comment]
I've understand this. will do in later.

**Comment by mattn** [comment]
https://metacpan.org/release/MATTN/Devel-CheckLib-1.04
