### ISSUE TITLE
Warning: unable to close filehandle properly: Bad file descriptor during global destruction.

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Dist-Zilla#415]
In perl 5.21.6 I've been seeing this at the end of a `dzil release` (*not* `dzil build`):

    Warning: unable to close filehandle properly: Bad file descriptor during global destruction.

I'm not sure what the cause is, but it might be related to prompts.  We just need to strace it...

**Comment by rjbs** [comment]
I haven't seen this (lately?).  You?

**Comment by karenetheridge** [comment]
I haven't seen it lately. It may have been an issue with that blead release or something that got fixed in a Term module?

**Comment by rjbs** [comment]
:ascii-art-shrug:
