### ISSUE TITLE
AutoPrereqs not getting prereqs from xt tests with ExtraTests plugin

### ISSUE THREAD

**Issue by robrwo** [rjbs/Dist-Zilla#416]
Using a dist.ini with the following options (in that order):
```ini
[@Basic]      ; (actually filtered, but not removing ExtraTests)
[AutoPrereqs]
[CPANFile]
```
I've added an `xt/release/no-fixme.t` file with the following:
```perl
use Test::Fixme;
run_tests(...);
```
It does not add Test::Fixme to the requirements in cpanfile.

It does after moving the test into the `t` dir.

**Comment by dolmen** [comment]
Could you show us the real dist.ini, with all plugins in the order of your dist.ini?

**Comment by robrwo** [comment]
I am able to reproduce it with a very minimal file:
```ini
[PkgVersion]
[@Basic]
[AutoPrereqs]
[CPANFile]
```

**Comment by karenetheridge** [comment]
If the test is a release test (not run for users), then having the prereqs added to cpanfile under 'test_requires' would be the wrong thing to do anyway.  Test::Fixme should be a develop prereq (or simply left out entirely).

The AutoPrereqs plugin understands this: https://github.com/rjbs/Dist-Zilla/blob/master/lib/Dist/Zilla/Plugin/AutoPrereqs.pm#L148

**Comment by rjbs** [comment]
It seems useful/reasonable to add another fileset like `[ develop => 'found_xt_files' ]`, no?

**Comment by karenetheridge** [comment]
@rjbs yes, and indeed you have some PRs from a year ago that do so.

**Comment by dolmen** [comment]
@rjbs see #192.

**Comment by robrwo** [comment]
Yes, I think it makes more sense to add them as prereqs for developers.

**Comment by rjbs** [comment]
I *think* this is covered by #192.
