### ISSUE TITLE
Prereq Path::Tiny needs to be specified with min version number 0.052

### ISSUE THREAD

**Issue by zhouzhen1** [rjbs/Dist-Zilla#427]
I was trying to install Dist-Zilla 5.032 today on linux, perl5.10.1, and test failed at t/plugins/manifest.t. It reported like 

Error sysopen on '/some/paths/source/file'with'quotes/or/backslash.txt013254': No such file or directory at /some/other/paths/Dist/Zilla/Tester.pm line 154. 

I looked at Dist/Zilla/Tester.pm and thought it could be problem of Path::Tiny. And we had only Path::Tiny 0.040 in our company. So I downloaded and tried 3 other versions of Path::Tiny, 0.050, 0.052 and 0.061(latest). It turned out that 0.050 also failed this test like above, but 0.052 and 0.061 were good. 

On the changeslog of Path::Tiny (https://metacpan.org/changes/distribution/Path-Tiny) it says like below, and I think it probably relates to an issue that got fixed in Path::Tiny 0.052. 
```
0.052     2014-01-14 15:58:03-05:00 America/New_York
 
    [FIXED]
 
    - Backslash-to-slash conversion now only happens on Windows
      (since backslash is legal on Unix, we must allow it)
 
0.051     2013-12-20 07:34:14 America/New_York
 
    [FIXED]
 
    - Fixed file order bug in the new test file
```

**Comment by rjbs** [comment]
Thanks!  I've merged a fix that will go out in the next release!
