### ISSUE TITLE
Add a %P format to put the PAUSE id of the releaser in NextRelease

### ISSUE THREAD

**Issue by neilbowers** [rjbs/Dist-Zilla#431]
In the format for NextRelease I'd like to put:

    format = %-4v %{yyyy-MM-dd}d %P

So that I'd get the line:

    0.12 2015-03-02 NEILB

Where `%P` (or some other symbol) is "the PAUSE id of the person doing the release".

**Comment by rjbs** [comment]
* add a `cpanid` method to UploadToCPAN that just returns `$self->username`
* the %P format will find the `Releaser` plugin for the zilla...
* ...make sure that it has a cpanid method...
* ...and use that!

**Comment by rjbs** [comment]
```perl
my ($releaser) = $self->zilla->plugins_with('-Releaser');
$self->log_fatal("releaser doesn't provide cpanid, but %P used") unless $releaser->can('cpanid');
$releaser->cpanid;
```

^-- total guess?

**Comment by neilbowers** [comment]
\o/
