### ISSUE TITLE
5.035 metadata validation is failing on release_status

### ISSUE THREAD

**Issue by pwr22** [rjbs/Dist-Zilla#445]
Not broken in the previous version. Not sure exactly why but release_status is trying to be set to 'stable' when using a dev release version. Even fails when testing

To test please checkout the repo [here](https://github.com/pwr22/cloudflare-client) and try to run either of

    dzil build
    dzil test

**Comment by pwr22** [comment]
The errors were

    [DZ] writing CloudFlare-Client in .build/3NhtcbalBS
    [MetaYAML] Invalid META structure.  Errors found:
    [MetaYAML] 'stable' for 'release_status' is invalid for version '0.05_5' (release_status) [Validation: 2]
    [MetaYAML] Invalid META structure.  Errors found:
    [MetaYAML] 'stable' for 'release_status' is invalid for version '0.05_5' (release_status) [Validation: 2] at /home/peter/.perlbrew/libs/5.20.1@general/lib/perl5/x86_64-linux/Moose/Meta/Method/Delegation.pm line 110.

**Comment by karenetheridge** [comment]
It looks like the `release_status` builder sub is not looking at `$zilla->version` (if an underscore is found, that would imply a release_status of unstable). I suspect @dagolden was assuming a ReleaseStatusProvider plugin would perform that duty, but I wonder if it should be made part of core.

**Comment by dagolden** [comment]
Weird.  I definitely had that in at one point. Perhaps it got lost in refactoring is_trial.  Let me put together a test and a patch.

**Comment by dakkar** [comment]
Another reason why it's not working: `::Command::build` always sets `$ENV{RELEASE_STATUS}`, even when `--trial` is not given (`::Command::release` does as well).

**Comment by rjbs** [comment]
I think this will be fixed by #446.

**Comment by rjbs** [comment]
I believe this is now fixed.  Please tell me if not!
