### ISSUE TITLE
Three strange test failures ("Cannot determine local time zone") when installing Dist::Zilla on Windows 7

### ISSUE THREAD

**Issue by klaus03** [rjbs/Dist-Zilla#450]
I am getting three strange test failures ("Cannot determine local time zone") when installing Dist::Zilla (version 5.036) on my system (Windows 7, x64, Strawberry Perl 5.020):

    t/plugins/distmeta.t ......... Dubious, test returned 2 (wstat 512, 0x200)
    t/plugins/license.t .......... Dubious, test returned 2 (wstat 512, 0x200)
    t/plugins/readme.t ........... Dubious, test returned 2 (wstat 512, 0x200)

    Cannot determine local time zone
    # Tests were run but no plan was declared and done_testing() was not seen.
    # Looks like your test exited with 2 just after 6.
    t/plugins/distmeta.t ......... 
    Dubious, test returned 2 (wstat 512, 0x200)
    All 6 subtests passed 

    Cannot determine local time zone
    # Child (non-ASCII author) exited without calling finalize()
    #   Failed test 'non-ASCII author'
    #   at C:/Strawberry/perl/lib/Test/Builder.pm line 279.
    # Tests were run but no plan was declared and done_testing() was not seen.
    # Looks like your test exited with 2 just after 2.
    t/plugins/license.t .......... 
    Dubious, test returned 2 (wstat 512, 0x200)
    Failed 1/2 subtests 

    Cannot determine local time zone
    # Tests were run but no plan was declared and done_testing() was not seen.
    # Looks like your test exited with 2 just after 3.
    t/plugins/readme.t ........... 
    Dubious, test returned 2 (wstat 512, 0x200)
    All 3 subtests passed 

    Test Summary Report
    -------------------
    t/plugins/distmeta.t       (Wstat: 512 Tests: 6 Failed: 0)
    Non-zero exit status: 2
    Parse errors: No plan found in TAP output

    t/plugins/license.t        (Wstat: 512 Tests: 2 Failed: 1)
    Failed test:  2
    Non-zero exit status: 2
    Parse errors: No plan found in TAP output

    t/plugins/readme.t         (Wstat: 512 Tests: 3 Failed: 0)
    Non-zero exit status: 2
    Parse errors: No plan found in TAP output

    Files=47, Tests=435, 92 wallclock secs ( 0.30 usr +  0.16 sys =  0.45 CPU)
    Result: FAIL
    Failed 3/47 test programs. 1/435 subtests failed.
    dmake.exe:  Error code 255, while making 'test_dynamic'

**Comment by karenetheridge** [comment]
Any chance you can get a stack trace on that?

- install Devel::Confess
- `perl Makefile.PL; make`
- and then either `PERL5OPT=d:Confess make test`, or run a test individually with `perl -Mblib -d:Confess t/foo.t`

**Comment by klaus03** [comment]
No problem, here is the dump (I have DateTime::TimeZone::Local version 1.85 on my system)

    C:\Users\Cat64\Documents\CPan\Dist-Zilla-5.036>perl -Mblib -d:Confess t/plugins/readme.t
    ok 1 - copyright appears in README file
    ok 2 - 'same terms as perl'-ish text appears in README
    ok 3 - dist name appears in README
    Cannot determine local time zone
     at C:/Strawberry/perl/vendor/lib/DateTime/TimeZone/Local.pm line 22.
            DateTime::TimeZone::Local::TimeZone("DateTime::TimeZone::Local") called at C:/Strawberry/per
    l/vendor/lib/DateTime/TimeZone.pm line 54
            DateTime::TimeZone::new(undef, "name", "local") called at C:/Strawberry/perl/vendor/lib/Date
    Time.pm line 2062
            DateTime::set_time_zone(DateTime=HASH(0x73bc368), "local") called at C:/Strawberry/perl/vend
    or/lib/DateTime.pm line 540
            DateTime::from_epoch(undef, "epoch", 1431193147, "time_zone", "local") called at C:\Users\Ca
    t64\Documents\CPan\Dist-Zilla-5.036\blib\lib/Dist/Zilla/Plugin/NextRelease.pm line 26
            Dist::Zilla::Plugin::NextRelease::__ANON__[C:\Users\Cat64\Documents\CPan\Dist-Zilla-5.036\bl
    ib\lib/Dist/Zilla/Plugin/NextRelease.pm:28](Dist::Zilla::Plugin::NextRelease=HASH(0x690fb28), "yyyy-
    MM-dd HH:mm:ssZZZZZ VVVV") called at C:\Strawberry\perl\site\lib/String/Formatter.pm line 276
            String::Formatter::method_replace(String::Formatter=HASH(0x6871d90), ARRAY(0x6872fe0), Dist:
    :Zilla::Plugin::NextRelease=HASH(0x690fb28)) called at C:\Strawberry\perl\site\lib/String/Formatter.
    pm line 114
            String::Formatter::format(String::Formatter=HASH(0x6871d90), "%-9v %{yyyy-MM-dd HH:mm:ssZZZZ
    Z VVVV}d%{ (TRIAL RELEASE)}T", Dist::Zilla::Plugin::NextRelease=HASH(0x690fb28)) called at C:\Strawb
    erry\perl\site\lib/String/Formatter.pm line 18
            String::Formatter::__ANON__[C:\Strawberry\perl\site\lib/String/Formatter.pm:18]("%-9v %{yyyy
    -MM-dd HH:mm:ssZZZZZ VVVV}d%{ (TRIAL RELEASE)}T", Dist::Zilla::Plugin::NextRelease=HASH(0x690fb28))
    called at C:\Users\Cat64\Documents\CPan\Dist-Zilla-5.036\blib\lib/Dist/Zilla/Plugin/NextRelease.pm l
    ine 96
            Dist::Zilla::Plugin::NextRelease::section_header(Dist::Zilla::Plugin::NextRelease=HASH(0x690
    fb28)) called at C:\Users\Cat64\Documents\CPan\Dist-Zilla-5.036\blib\lib/Dist/Zilla/Plugin/NextRelea
    se.pm line 114
            Dist::Zilla::Plugin::NextRelease::munge_files(Dist::Zilla::Plugin::NextRelease=HASH(0x690fb2
    8)) called at C:\Users\Cat64\Documents\CPan\Dist-Zilla-5.036\blib\lib/Dist/Zilla/Dist/Builder.pm lin
    e 323
            Dist::Zilla::Dist::Builder::build_in(Dist::Zilla::Tester::_Builder=HASH(0x5f98c68), Path::Cl
    ass::Dir=HASH(0x5deebd8)) called at C:\Users\Cat64\Documents\CPan\Dist-Zilla-5.036\blib\lib/Dist/Zil
    la/Tester.pm line 187
            Class::MOP::Class:::around(CODE(0x4787e00), Dist::Zilla::Tester::_Builder=HASH(0x5f98c68)) c
    alled at C:/Strawberry/perl/vendor/lib/Class/MOP/Method/Wrapped.pm line 158
            Class::MOP::Method::Wrapped::__ANON__[C:/Strawberry/perl/vendor/lib/Class/MOP/Method/Wrapped
    .pm:158](Dist::Zilla::Tester::_Builder=HASH(0x5f98c68)) called at C:/Strawberry/perl/vendor/lib/Clas
    s/MOP/Method/Wrapped.pm line 87
            Dist::Zilla::Tester::_Builder::build_in(Dist::Zilla::Tester::_Builder=HASH(0x5f98c68)) calle
    d at C:\Users\Cat64\Documents\CPan\Dist-Zilla-5.036\blib\lib/Dist/Zilla/Dist/Builder.pm line 302
            Dist::Zilla::Dist::Builder::build(Dist::Zilla::Tester::_Builder=HASH(0x5f98c68)) called at t
    /plugins/readme.t line 46
    # Tests were run but no plan was declared and done_testing() was not seen.
    # Looks like your test exited with 2 just after 3.
    
    C:\Users\Cat64\Documents\CPan\Dist-Zilla-5.036>

**Comment by karenetheridge** [comment]
This looks like a  DateTime::TimeZone::Local issue, or possibly a problem with your local system configuration. Have you tried upgrading DateTime::TimeZone::Local? Does it pass its tests?

**Comment by klaus03** [comment]
I have upgraded DateTime::TimeZone::Local from version 1.85 to version 1.88, but still, the problem persists. It seems that this is an issue with DateTime::TimeZone::Local itself,

Thanks for your time, I agree, this doesn't look like an issue with Dist::Zilla, I will now myself look into DateTime::TimeZone::Local and my local system configuration.

**Comment by karenetheridge** [comment]
see also: https://rt.cpan.org/Ticket/Display.html?id=103275
