### ISSUE TITLE
"Cannot determine local time zone" on Windows

### ISSUE THREAD

**Issue by chorny** [rjbs/Dist-Zilla#458]
http://www.cpantesters.org/cpan/report/68de28f1-6c14-1014-b6ce-63412d4acde3

New DateTime::TimeZone has Windows support in standalone distribution DateTime::TimeZone::Local::Win32 . It should be required on Windows in addition to DateTime.

**Comment by rjbs** [comment]
Done in a45e8e4, thanks.
