### ISSUE TITLE
Each other build fails

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla#462]
Fedora 22 for x86_64, perl-5.20.2-326.fc22.x86_64, Dist::Zilla 5.037 (installed to user directory via local::lib).

`dist.ini`:

    name                = Foo
    version             = 0.001_001
    author              = John Doe
    license             = Perl_5
    main_module         = lib/Foo.pm
    abstract            = A test

    [GatherDir]
    [GenerateFile]
        filename = lib/Foo.pm
        content  = package Foo;
        content  = 1;
    [Manifest]

This `dist.ini` is the only source file. Module is generated. The first build completes successfully:

    $ dzil build
    [DZ] beginning to build Foo
    [DZ] writing Foo in Foo-0.001_001
    [DZ] building archive with Archive::Tar::Wrapper
    [DZ] writing archive to Foo-0.001_001-TRIAL.tar.gz
    [DZ] built in Foo-0.001_001

But the next build fails:

    $ dzil build
    [DZ] beginning to build Foo
    [DZ] writing Foo in Foo-0.001_001
    Error open (<:unix) on 'Foo-0.001_001/MANIFEST': No such file or directory at .../lib/perl5/Dist/Zilla/File/OnDisk.pm line 34.

The next build completes successfully. The next fails again. And so on.

I guess the reason for failure is GatherDir plugin — it grabs really all files in the directory:

    $ dzil build -v
    [DZ] reading configuration using Dist::Zilla::MVP::Reader::Finder
    [GatherDir] online, Dist::Zilla::Plugin::GatherDir v5.037
    [GenerateFile] online, Dist::Zilla::Plugin::GenerateFile v5.037
    [Manifest] online, Dist::Zilla::Plugin::Manifest v5.037
    [DZ] beginning to build Foo
    [GatherDir] considering .
    [GatherDir] considering dist.ini
    [GatherDir] considering Foo-0.001.tar.gz
    [GatherDir] considering Foo-0.001
    [GatherDir] considering Foo-0.001/dist.ini
    [GatherDir] considering Foo-0.001/Foo-0.001.tar.gz
    [GatherDir] considering Foo-0.001/MANIFEST
    [GatherDir] considering Foo-0.001/Foo-0.001
    [GatherDir] considering Foo-0.001/Foo-0.001/dist.ini
    [GatherDir] considering Foo-0.001/Foo-0.001/Foo-0.001.tar.gz
    [GatherDir] considering Foo-0.001/Foo-0.001/Foo-0.001
    [GatherDir] considering Foo-0.001/Foo-0.001/Foo-0.001/dist.ini
    [GatherDir] considering Foo-0.001/Foo-0.001/Foo-0.001/Foo-0.001.tar.gz
    [GatherDir] considering Foo-0.001/lib
    [GatherDir] considering Foo-0.001/lib/Foo.pm
    [GatherDir] adding file dist.ini
    [GatherDir] adding file Foo-0.001.tar.gz
    [GatherDir] adding file Foo-0.001/dist.ini
    [GatherDir] adding file Foo-0.001/Foo-0.001.tar.gz
    [GatherDir] adding file Foo-0.001/MANIFEST
    [GatherDir] adding file Foo-0.001/Foo-0.001/dist.ini
    [GatherDir] adding file Foo-0.001/Foo-0.001/Foo-0.001.tar.gz
    [GatherDir] adding file Foo-0.001/Foo-0.001/Foo-0.001/dist.ini
    [GatherDir] adding file Foo-0.001/Foo-0.001/Foo-0.001/Foo-0.001.tar.gz
    [GatherDir] adding file Foo-0.001/lib/Foo.pm
    [GenerateFile] adding file lib/Foo.pm
    [Manifest] adding file MANIFEST
    [DZ] writing Foo in Foo-0.001
    Error open (<:unix) on 'Foo-0.001/MANIFEST': No such file or directory at .../lib/perl5/Dist/Zilla/File/OnDisk.pm line 34.

I think GatherDir could be a bit more intellectual to exclude tarball and directory left from the previous build for two reasons:

1. "Most users just need: [GatherDir]" — from Dist::Zilla documentation.
2. Third build completes successfully, producing bad tarball — it contains three more tarballs within, some of them also contains other tarballs within.

**Comment by karenetheridge** [comment]
It's not correct to use `[GatherDir]` on its own without configuring some files/directories to be skipped, and changing its default behaviour will break everyone else's build.

You'll have much better luck if you start with `[@Basic]` in your dist.ini, which contains `[PruneFiles]` that excludes the things you mention.

Have you seen this documentation? http://dzil.org/tutorial/start.html

**Comment by van-de-bugger** [comment]
> It's not correct to use [GatherDir] on its own without configuring some files/directories to be skipped, 

It such a case, the [documentation on GatherDir](https://metacpan.org/pod/Dist::Zilla::Plugin::GatherDir) should not say "Most users just need: [GatherDir]", it should say instead:

> Most users just need: 
> [GatherDir]
> [PruneFiles]

...or whatever will work with no surprises (PruneCruft, maybe?).

> Have you seen this documentation? http://dzil.org/tutorial/start.html

I have seen that site. Very nice for advertising Dist::Zilla, but it provides little help (imho). For example, let us read [Building a Dist from Scratch](http://dzil.org/tutorial/new-dist.html) from the position of a newbie. Install Dist::Zilla (any link to explanation how to it? I do not require dzil.org describes it, a link to external resource will work), dzil setup, dzil new — fine, then:

> It's crucial that you understand what's in that "@Basic" bundle. That is almost the entire configuration that will be used to build your distribution. If you add more plugins that conflict with the ones in the basic bundle, but you had no idea what was in "@Basic", you will be confused.

But how to understand what's in that bundle? It does not provide any clue for a beginner. For you it may be obvious, but it would be great think about newbies and provide, for example, link to [this page](https://metacpan.org/pod/Dist::Zilla::PluginBundle::Basic#DESCRIPTION).

**Comment by rjbs** [comment]
I've added a note in c31c58f about using PruneCruft.  I added a link to `@Basic` in dzil.org c4e18fa
