### ISSUE TITLE
dzil build: -v is not documented

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla#463]
Neither `dzil help` nor `dzil help build` documents `-v` option.

**Comment by karenetheridge** [comment]
```
: [ether@jaeger]$; dzil help
dzil <command> [-Iv] [long options...]
	-v[=STR...] --verbose[=STR...]    log additional output
	-I STR... --lib-inc STR...        additional @INC dirs

Available commands:
...
```

Perhaps each sub-command should have a note "see also "dzil help", for options accepted by all commands"

**Comment by van-de-bugger** [comment]
I have dzil v5.037 — the last published release on CPAN. I see no help on options:

    $ dzil --version
    dzil (Dist::Zilla::App) version 5.037 (/home/lev/.usr/bin/dzil)

    $ dzil help
    Available commands:

        commands: list the application's commands
            help: display a command's help screen

             add: add modules to an existing dist
      authordeps: list your distribution's author dependencies
           build: build your dist
           clean: clean up after build, test, or install
         install: install your dist
        listdeps: print your distribution's prerequisites
             new: mint a new dist
             nop: do nothing: initialize dzil, then exit
         release: release your dist
             run: run stuff in a dir where your dist is built
           setup: set up a basic global config file
           smoke: smoke your dist
            test: test your dist
           xtest: run xt tests for your dist

**Comment by rjbs** [comment]
App::Cmd or Getopt::Long::Descriptive out of date?

**Comment by van-de-bugger** [comment]
App::Cmd 0.326
Getopt::Long::Descriptive 0.099

Updating App::Cmd to 0.327 helps, thanks.

**Comment by van-de-bugger** [comment]
$ dzil help
    dzil <command> [-Iv] [long options...]
    	-v[=STR...] --verbose[=STR...]    log additional output
    	-I STR... --lib-inc STR...        additional @INC dirs

BTW, What does `STR` argument of `-v` option mean?

**Comment by rjbs** [comment]
You can say "dzil -v PLUGIN build" and it will only turn on verbose for that one plugin

**Comment by rjbs** [comment]
I have added a higher prereq for App::Cmd.

**Comment by van-de-bugger** [comment]
I am almost ready to close the issue. However, I have few more questions:

    $ dzil help
    dzil <command> [-Iv] [long options...]
        -v[=STR...] --verbose[=STR...]    log additional output
        -I STR... --lib-inc STR...        additional @INC dirs
    ...

Is it possible to replace generic `STR` with something more helpful? Could you add few more words to `-v` help?


    $ dzil help
    dzil <command> [-Iv] [long options...]
        -v[=PLUGIN...] --verbose[=PLUGIN...]    log additional output from PLUGIN (all plugins by default)
        -I DIR... --lib-inc DIR...        additional @INC dirs
    ...

**Comment by rjbs** [comment]
It is not possibly right now to replace the STR.  Probably it would be not-too-hard to add that (to Getopt::Long::Descriptive).

**Comment by van-de-bugger** [comment]
Ok. I'll closing the issue then.
