### ISSUE TITLE
TextTemplate role: it is not possible to pass PACKAGE option to underlying Text::Template

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla#473]
Hi, currently (v5.037) method `fill_in_string` of `TextTemplate` role creates a new instance of `Text::Template` class, and then calls `fill_in` method on the instance:

    sub fill_in_string {
      my ($self, $string, $stash, $arg) = @_;

      $self->log_fatal("Cannot use undef as a template string")
        unless defined $string;

      my $tmpl = Text::Template->new(
        TYPE       => 'STRING',
        SOURCE     => $string,
        DELIMITERS => $self->delim,
        BROKEN     => sub { my %hash = @_; die $hash{error}; },
        %$arg,
      );

      $self->log_fatal("Could not create a Text::Template object from:\n$string")
        unless $tmpl;

      my $content = $tmpl->fill_in(HASH => $stash);

      $self->log_fatal("Filling in the template returned undef for:\n$string")
        unless defined $content;

      return $content;
    }

If a plugin consumed `TextTemplate` role calls

    $self->fill_in_string( $str, { ... }, { PACKAGE => 'Q' } );

the option `PACKAGE` has no effect, because `fill_in_string` passes its third argument to the constructor, while `PACKAGE` is option of `fill_in`.

Probably, the simplest method to fix the issue is passing `%$arg` to `fill_in` too, e. g.:

      my $content = $tmpl->fill_in(HASH => $stash, %$arg);

I think it is possible because `Text::Template` implements its `fill_this_in`  in such a way:

    sub fill_this_in {
      my $pack = shift;
      my $text = shift;
      my $templ = $pack->new(TYPE => 'STRING', SOURCE => $text, @_)
        or return undef;
      $templ->compile or return undef;
      my $result = $templ->fill_in(@_);
      $result;
    }

Note: `@_` passed to `new` and to `fill_in`.

**Comment by rjbs** [comment]
Sounds good, I've made this change in c6b3594.
