### ISSUE TITLE
provide_license: incorrect documentation

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla#477]
Documentation on [provide_license](https://metacpan.org/pod/Dist::Zilla::Role::LicenseProvider#provide_license-copyright_holder-copyright_year) method of LicenseProvider role is incorrect:

    provide_license($copyright_holder, $copyright_year)

Actually, `DistZilla` passes **one** argument to `provide_license`, which is `HashRef` with **two** keys, `copyright_holder` and `copyright_year`.

**Comment by karenetheridge** [comment]
patches welcome!

**Comment by rjbs** [comment]
Thanks, @van-de-bugger.  While a patch to fix the docs is nice, so is a report of a factual error.

@karenetheridge, "Patches welcome" is way too often read as "if you care so much, why don't *you* fix it?"  I would rather it not become the initial, context-free reply to bug reports sent to me.

**Comment by karenetheridge** [comment]
It's simply meant as a statement of "the author of this is *really* busy, and even pull requests sit for months because he scarcely has time to apply them, so if you are hoping for something this century, a pull request is going to be your best bet".  For people who *can't* submit patches, more accomodation is given, but pull requests are always better for people who know their way around git and understand the basics of the code in question.

**Comment by van-de-bugger** [comment]
@rjbs: You are welcome.

@karenetheridge:  Let me explain: (1) For a person who already has everything in place (e. g. for author or current developer/maintainer) the fix is trivial, efforts spent on the fix are comparable with efforts to write a message "patches welcome!". I will spend much more time to clone the repo, fix the problem, commit it back, make a pull request, whatever-else-i-am-not-aware-of because I am not very familiar with git and github. (I done it once or twice, but it was quite a long time ago.) (2) Probably you know what should be fixed — code or doc, but I don't. (Ok, now I see rjbs wrote: "a patch to fix a doc".) (3) My writing abilities in English are not very good (at least, I am not happy with them), I hate to write documentation, I spend so much time to write doc for my own modules, so I would like to left a duty for fixing this particular problem to someone else. (4) I have reported the issue — that's about a half of work, please do not request more from me.

**Comment by karenetheridge** [comment]
@van-de-bugger Okay, I had gotten the impression from your recent releases that you were quite familiar with the inner workings of Dist::Zilla by now, and thought that you were ready to try submitting patches. Sorry!
