### ISSUE TITLE
Wishlist: ReportPhase functionality should be a part of Dist::Zilla.

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla#487]
There is a nice plugin [`ReportPhase`](https://metacpan.org/pod/Dist::Zilla::Plugin::ReportPhase). However, there are few problems with it:

1. It seems it is not actively maintained now. There are few issues opened 10 months ago.
2. The plugin can be misused easily. For example, `[ReportPhase/Phase_Begins]` must be at the very top of `dist.ini`, while `[ReportPhase/Phase_Ends]` must be at the very bottom of `dist.ini`, otherwise user will have misleading output. (It is not clearly documented in `ReportPhase` documentation and is not obvious for a newbie developer.)
3. If `Dist::Zilla` introduces a new phase, the plugin should be updated.

`ReportPhase` functionality can be easily implemented directly in `Dist::Zilla`. For example,

    # Builder.pm, line ~348:
    $self->log_debug( 'gather_files begins...' ); # new line
    $_->gather_files       for @{ $self->plugins_with(-FileGatherer) };
    $self->log_debug( 'gather_files finished' ); # new line

It could be easily implemented as Dist::Zilla method to avoid repeating the same code in each phase:

    sub phase {
        my ( $self, $phase, $role ) = @_;
        $self->log_debug( [ '%s begins', $phase ] );
        $_->$phase for @{ $self->plugins_with("-$role") };
        $self->log_debug( [ '%s finished', $phase ] );
    };

then:

    # Builder.pm, line ~348:
    # $_->gather_files       for @{ $self->plugins_with(-FileGatherer) }; # old code
    $self->phase('gather_files', 'FileGatherer' ); # new code

Implementing such debug output directly in `Dist::Zilla` has numerous advantages:

1. No delay between adding a phase and supporting it by external plugin.
2. It cannot be misused, output is always correct.
3. Debug output can be turned on and off from command line, there is no need to add or remove lines in different parts of `dist.ini`.

**Comment by rjbs** [comment]
Sounds reasonable.  I'd accept a PR.

**Comment by van-de-bugger** [comment]
Does PR means "pull request"? 

`Dist-Zilla` repo has more than dozen of branches. Which branch should be forked?

**Comment by rjbs** [comment]
Yes, and master.

**Comment by rjbs** [comment]
I'm closing this because #501 replaces it.
