### ISSUE TITLE
AutoPrereqs: runtime vs test

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla#492]
Consider `dist.ini`:

    name     = Assa
    version  = v0.1.0
    abstract = Test

    [GenerateFile/lib/Assa.pm]
        filename = lib/Assa.pm
        content  = package Assa;
        content  = use strict v5.10.0;
        content  = 1;
    [GenerateFile/t/test.t]
        filename = t/test.t
        content  = #!perl
        content  = use strict v5.12.0;
        content  = exit 0;
    [GatherDir]
    [PruneCruft]
    [AutoPrereqs]
    [MetaJSON]

It is self-containing and does not require external files. Note: `lib/Assa.pm` uses `strict` v5.10.0, while `t/test.t` uses `strict` v5.12.0.

    $ dzil build
    [DZ] beginning to build Assa
    [DZ] writing Assa in Assa-v0.1.0
    [DZ] building archive with Archive::Tar::Wrapper
    [DZ] writing archive to Assa-v0.1.0.tar.gz
    [DZ] built in Assa-v0.1.0

Now look at `META.json`:

    $ cat Assa-v0.1.0/META.json 
    ...
       "prereqs" : {
          "runtime" : {
             "requires" : {
                "strict" : "v5.12.0"
             }
          },
          "test" : {
             "requires" : {
                "strict" : "v5.12.0"
    ...

Accordingly to `META.json`, runtime requires `strict` v5.12.0, which is incorrect, since `lib/Assa.pm` uses `strict` v5.10.0, not v5.12.0.

`Dist::Zilla` 5.038.

**Comment by karenetheridge** [comment]
https://metacpan.org/source/RJBS/Dist-Zilla-5.039/lib/Dist/Zilla/Prereqs.pm#L105-129

**Comment by van-de-bugger** [comment]
Err... I did not get what you mean by providing that link. Do you mean I should update to Dist::Zilla 5.039? Before submitting this bug, I checked Dist::Zilla 5.039 Changes:

> update required version of MooseX::Role::Parameterized; older versions work, but can cause a bunch of unwanted warnings

...and thought the change is not relevant for my problem. Anyway, today I have updated Dist::Zilla to the 5.039, the bug is still present.

BTW, comment in lines 105/107 is not very good. It talks about "a long-standing CPAN.pm bug...". It would be nice if the comment also provides a link to the bug at CPAN RT or github or another-place-where-CPAN.pm-tracks-its-bugs.

**Comment by karenetheridge** [comment]
> Err... I did not get what you mean by providing that link.

The linked code is responsible for the behaviour you are observing.

I don't know the details of the CPAN bug. I didn't write this code nor the comment.

**Comment by dolmen** [comment]
> BTW, comment in lines 105/107 is not very good. It talks about "a long-standing CPAN.pm bug..."

This just means that fixing the issue you reported would raise problems for some machines installing your module.
I didn't write either this code nor the comment.

**Comment by dolmen** [comment]
I suggest to use `Test::Is "perl v5.12";` or `Test::Requires "v5.12"` in your test and to tell AutoPrereqs to skip your test (`skip=t/test.t`).

**Comment by rjbs** [comment]
The source of the code was a fix for https://github.com/rjbs/Dist-Zilla/issues/238
