### ISSUE TITLE
GatherDir fails tests on perl 5.8.5, 5.8.6

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Dist-Zilla#496]
http://matrix.cpantesters.org/?dist=Dist-Zilla+5.039

The symlink in the distribution isn't being picked up by File::Find::Rule, so I suspect something in File::Find is responsible. Unfortunately, File::Find is not dual-life so I cannot easily bisect.

```
  v5.8.5     1.07      
  v5.8.6     1.07      
  v5.8.7     1.09      
  v5.8.8     1.10      
```

FF 1.10: 3555aed31
FF 1.09: 0c52c6a9d
FF 1.07: be56ab1f8

**Comment by rjbs** [comment]
Will be fixed by v6. :-)

**Comment by rjbs** [comment]
You can get the diff in a perl repo with: `git diff perl-5.8.6..perl-5.8.7 -- lib/File/Find.pm`

....but still, fixed in six. :)
