### ISSUE TITLE
5.040 make test failure

### ISSUE THREAD

**Issue by gravattj** [rjbs/Dist-Zilla#502]
While running "make test" on centos 7, I received the following errors.  I tried 5.039 and had no issues.

===snip===
Manifying blib/man3/Dist::Zilla::Plugin::PodCoverageTests.3pm
Manifying blib/man3/Dist::Zilla::Plugin::Readme.3pm
Manifying blib/man3/Dist::Zilla::Plugin::MetaYAML.3pm
Manifying blib/man3/Dist::Zilla::Role::BuildRunner.3pm
[root@ip-10-168-29-107 Dist-Zilla-5.040]# ls
bin   Changes  cpanfile  lib      Makefile     MANIFEST   META.yml  MYMETA.json  pm_to_blib  README  todo
blib  corpus   dist.ini  LICENSE  Makefile.PL  META.json  misc      MYMETA.yml   profiles    t       xt
[root@ip-10-168-29-107 Dist-Zilla-5.040]# TEST_VERBOSE = 1 make test
-bash: TEST_VERBOSE: command not found
[root@ip-10-168-29-107 Dist-Zilla-5.040]# TEST_VERBOSE=1 make test
Skip blib/lib/auto/share/module/Dist-Zilla-MintingProfile-Default/default/extra-dist.ini (unchanged)
Skip blib/lib/auto/share/module/Dist-Zilla-MintingProfile-Default/default/profile.ini (unchanged)
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/commands/*.t t/diagnostics/*.t t/plugins/*.t
t/00-report-prereqs.t ........ # 
# Versions for all modules listed in MYMETA.json (including optional ones):
# 
# === Configure Requires ===
# 
#     Module                  Want Have
#     ----------------------- ---- ----
#     ExtUtils::MakeMaker      any 6.68
#     File::ShareDir::Install 0.06 0.08
# 
# === Build Requires ===
# 
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 6.68
# 
# === Test Requires ===
# 
#     Module                    Want     Have
#     ------------------------ ----- --------
#     CPAN::Meta::Check        0.011    0.012
#     CPAN::Meta::Requirements 2.121    2.133
#     ExtUtils::MakeMaker        any     6.68
#     ExtUtils::Manifest        1.66     1.70
#     File::Spec                 any     3.40
#     Software::License::None    any 0.103008
#     Test::FailWarnings         any    0.008
#     Test::Fatal                any    0.010
#     Test::File::ShareDir       any 1.001001
#     Test::More                0.96 1.001014
#     lib                        any     0.63
#     utf8                       any     1.09
# 
# === Test Recommends ===
# 
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150005
# 
# === Runtime Requires ===
# 
#     Module                                         Want       Have
#     ------------------------------------------ -------- ----------
#     App::Cmd::Command::version                      any      0.329
#     App::Cmd::Setup                               0.327      0.329
#     App::Cmd::Tester                              0.306      0.329
#     App::Cmd::Tester::CaptureExternal               any      0.329
#     Archive::Tar                                    any       2.04
#     CPAN::Meta::Converter                      2.101550   2.150005
#     CPAN::Meta::Merge                               any   2.150005
#     CPAN::Meta::Prereqs                        2.120630   2.150005
#     CPAN::Meta::Requirements                      2.121      2.133
#     CPAN::Meta::Validator                      2.101550   2.150005
#     CPAN::Uploader                             0.103004   0.103011
#     Carp                                            any       1.26
#     Class::Load                                    0.17       0.20
#     Config::INI::Reader                             any      0.025
#     Config::MVP::Assembler                          any   2.200010
#     Config::MVP::Assembler::WithBundles        2.200010   2.200010
#     Config::MVP::Reader                        2.101540   2.200010
#     Config::MVP::Reader::Findable::ByExtension      any   2.200010
#     Config::MVP::Reader::Finder                     any   2.200010
#     Config::MVP::Reader::INI                          2   2.101463
#     Config::MVP::Section                       2.200009   2.200010
#     Data::Dumper                                    any      2.145
#     Data::Section                              0.200002   0.200006
#     DateTime                                       0.44       1.04
#     Digest::MD5                                     any       2.54
#     Encode                                          any       2.51
#     ExtUtils::Manifest                             1.66       1.70
#     File::Copy::Recursive                           any       0.38
#     File::Find::Rule                                any       0.33
#     File::HomeDir                                   any       1.00
#     File::Path                                      any       2.09
#     File::ShareDir                                  any       1.03
#     File::ShareDir::Install                        0.03       0.08
#     File::Spec                                      any       3.40
#     File::Temp                                      any     0.2301
#     File::pushd                                     any      1.005
#     JSON::MaybeXS                                   any   1.002002
#     List::MoreUtils                                 any       0.33
#     List::Util                                     1.33       1.42
#     Log::Dispatchouli                          1.102220      2.012
#     Mixin::Linewise::Readers                      0.100      0.108
#     Module::CoreList                                any 5.20150920
#     Moose                                          0.92     2.1005
#     Moose::Role                                     any     2.1005
#     Moose::Util::TypeConstraints                    any     2.1005
#     MooseX::LazyRequire                             any       0.09
#     MooseX::Role::Parameterized                    1.01       1.07
#     MooseX::SetOnce                                 any   0.200002
#     MooseX::Types                                   any       0.35
#     MooseX::Types::Moose                            any       0.35
#     MooseX::Types::Path::Class                      any       0.06
#     MooseX::Types::Perl                             any   0.101343
#     PPI::Document                                   any      1.215
#     Params::Util                                    any       1.07
#     Path::Class                                    0.22       0.35
#     Path::Tiny                                    0.052      0.061
#     Perl::PrereqScanner                           1.016      1.023
#     Perl::Version                                   any      1.013
#     Pod::Eventual                              0.091480   0.093330
#     Scalar::Util                                    any       1.42
#     Software::License                          0.101370   0.103008
#     Software::LicenseUtils                          any   0.103008
#     String::Formatter                          0.100680   0.102084
#     String::RewritePrefix                         0.005      0.007
#     Sub::Exporter                                   any      0.986
#     Sub::Exporter::ForMethods                       any   0.100052
#     Sub::Exporter::Util                             any      0.986
#     Term::Encoding                                  any       0.02
#     Term::ReadKey                                   any       2.30
#     Term::ReadLine                                  any       1.09
#     Term::UI                                        any       0.36
#     Test::Deep                                      any      0.110
#     Text::Glob                                     0.08       0.09
#     Text::Template                                  any       1.45
#     Try::Tiny                                       any       0.22
#     YAML::Tiny                                      any       1.51
#     autodie                                         any       2.29
#     namespace::autoclean                            any       0.19
#     parent                                          any      0.225
#     strict                                          any       1.07
#     version                                         any     0.9912
#     warnings                                        any       1.13
# 
# === Runtime Recommends ===
# 
#     Module                Want    Have
#     --------------------- ---- -------
#     Archive::Tar::Wrapper 0.15 missing
#     Term::ReadLine::Gnu    any    1.26
# 
# === Runtime Suggests ===
# 
#     Module  Want    Have
#     ------- ---- -------
#     PPI::XS  any missing
# 
t/00-report-prereqs.t ........ ok   
t/commands/authordeps.t ...... ok   
t/commands/listdeps.t ........ 1/? 
#   Failed test 'all prereqs listed as output'
#   at t/commands/listdeps.t line 42.
# Comparing $data as a Bag
# Extra: 'Duplicate specification "help|help|h|?" for option "help"'

#   Failed test 'prereqs listed with versions for --versions'
#   at t/commands/listdeps.t line 51.
# Comparing $data as a Bag
# Extra: 'Duplicate specification "help|help|h|?" for option "help"'

#   Failed test 'develop prereqs included in output for --author'
#   at t/commands/listdeps.t line 61.
# Comparing $data as a Bag
# Extra: 'Duplicate specification "help|help|h|?" for option "help"'

#   Failed test 'develop prereqs included in output for --develop'
#   at t/commands/listdeps.t line 61.
# Comparing $data as a Bag
# Extra: 'Duplicate specification "help|help|h|?" for option "help"'
# Looks like you failed 4 tests of 4.
t/commands/listdeps.t ........ Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/4 subtests 
t/compile.t .................. ok       
t/diagnostics/main-module.t .. ok   
t/diagnostics/plugin-fail.t .. ok   
t/empty-abstract.t ........... ok   
===snip===

**Comment by rjbs** [comment]
Thanks.  Someone reported this earlier today, and we have been unable to reproduce it, but I did commit an almost certain fix.  You can try testing with latest head of App-Cmd, or enjoy the release I make in the next day or two. :-)

**Comment by rjbs** [comment]
new App-Cmd released
