### ISSUE TITLE
munge_files method allows code to screw up the iterated values

### ISSUE THREAD

**Issue by xsawyerx** [rjbs/Dist-Zilla#512]
To summarize [this ticket](https://github.com/yanick/Dist-Zilla-Plugin-CoalescePod/issues/1) on [CoalescePod](https://metacpan.org/pod/Dist::Zilla::Plugin::CoalescePod):

The `munge_files` method (in `Dist/Zilla/Role/FileMunger.pm`) uses `$self->zilla->files` to iterate over the files. Then when it calls `munge_file` on each one, if a munger prunes a file from that attribute, the `munge_files` iteration will get screwed up.

Per @rjbs, "this isn't okay". However, this is also a problem with `CoalescePod` using the wrong phase. Hence, I would be happy if we had:

1. A fix to this in dzil (simple PR, but I want to make sure I'm not wrong).
2. A fix to CoalescePod - I'm not sure which phase should be used. Help?

Thanks!

**Comment by karenetheridge** [comment]
I'll comment on the CoalesePod issue, as I don't think there is anything to do in Dist::Zilla itself.
