### ISSUE TITLE
add means to add a single file

### ISSUE THREAD

**Issue by rjbs** [rjbs/Dist-Zilla#528]
PERLANCAR wants a way to gather just one file.

Originally requested at https://rt.cpan.org/Ticket/Display.html?id=105583

**Comment by ambs** [comment]
Would a GatherFile plugin be the solution? -- need to create a PR for CPAN PR Challenge, and that might be it :-)

**Comment by karenetheridge** [comment]
I implemented this in https://github.com/rjbs/Dist-Zilla/pull/549.
