### ISSUE TITLE
:NoFiles file finder.

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla#572]
I tested bunch of file finders (`Dist::Zilla` 6.008):

    :AllFiles
    :ShareFiles
    :TestFiles
    :ExtraTestFiles
    :InstallModules
    :IncModules 
    :ExecFiles
    :PerlExecFiles

All these filefinders returns arrayref to empty array if there are no files in the category.

`:NoFiles` file finder differs. It returns just `undef`. Wouldn't it better to return arrayref to empty array, like it do others?

**Comment by rjbs** [comment]
You're quite right!  I've fixed this in git.
