### ISSUE TITLE
please do a 5.048 release, to stay on cpan

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Dist-Zilla#585]
see https://github.com/andk/cpanpm/pull/111#issuecomment-294037875 -- another release of the 5.x series, with the test fix for Moose applied, would be helpful

cc @dolmen

**Comment by rjbs** [comment]
It won't get indexed, because it will be too low a version, right?  So does it matter who does this upload?

**Comment by karenetheridge** [comment]
cpanm cares if earlier versions are uploaded by an authorized maintainer, to protect users from rogue uploads.

Plus, it would be nice if the release were tagged in the github repository.

**Comment by karenetheridge** [comment]
This continues to be at the top of my wish list for Dist-Zilla fixes.

(Another reason for you to do the release, other than cpanm respecting it, is that it would get a proper branch + tag in the repository.)

**Comment by karenetheridge** [comment]
\#oslo

> This continues to be at the top of my wish list for Dist-Zilla fixes.

**Comment by rjbs** [comment]
Your wish is my command.  🙇
