### ISSUE TITLE
Missing TestRunner Plugin

### ISSUE THREAD

**Issue by nancyyaweili** [rjbs/Dist-Zilla#592]
Hi,

I am trying to use Dist::Zilla to replace our current release process. I was following the tutorial and tried to put Dist::Zilla in my current package. However, when running dzil test, it complains about "Missing TestRunner plugin". I was under the impression that this command should just run similar to "prove -lv t". 

I've tried to google with no avail. I wrote a small TestRunner plugin and this seems to have fixed the problem. However, this doesn't seem to be the right move for Dist::Zilla. Could you please advise? Thanks. 
Nancy

**Comment by karenetheridge** [comment]
Could you paste the dist.ini that you are using? Normally it would contain either `[@Basic]` or `[MakeMaker]` -- MakeMaker is the plugin that provides the TestRunner.

**Comment by nancyyaweili** [comment]
Thanks karenetheridge for your quick reply. I was trying to customerize the basic bundle and realized that I removed MakeMaker from the list. After I added MakeMaker into the list, dzil test worked. 

My intention was I don't need MakeMaker but I need TestRunner which I manually added to dist.ini. I'll take a closer look at the MakeMaker code and see if I can do this.  

Thanks again.
