### ISSUE TITLE
I would like to create the META.json file without develop dependencies

### ISSUE THREAD

**Issue by skirmess** [rjbs/Dist-Zilla#614]
I would like to create the META.json file without develop dependencies.

In my opinion, xt tests should not be included in the distribution as they are of no use to the end user of the distribution. xt tests should stay in the repository. Same for the cpanfile, which isn't needed in the distribution.

I would therefore like to create a META.json file without develop dependencies in the distribution and a cpanfile with develop dependencies only in the repository. I was able to achieve that by hacking the MetaJSON plugin to include this line:

`    delete $output->{prereqs}{develop};`

Does that somehow make sense and would it be possible to get an option integrated into MetaJSON to exclude develop dependencies on demand?

**Comment by karenetheridge** [comment]
> would it be possible to get an option integrated into MetaJSON to exclude develop dependencies on demand

That's not the appropriate place to make that change -- if you want to drop all develop prereqs, you should do it directly in the prereqs data structure (where `[MetaJSON]` is just one of many plugins that consume that data).

You can achieve what you want by:

* updating your file-gathering plugin(s) to exclude xt/
* writing a plugin that drops all develop prereqs from the prereqs data structure (and run it after all other PrereqSource plugins) - you can do this with code right in the repository (there's no need to release it to cpan)

But I should caution you that "they of no use to the end user" is not necessarily true -- if it were, surely other distributions would be doing this already?

**Comment by skirmess** [comment]
>  if you want to drop all develop prereqs, you should do it directly in the prereqs data structure (as `[MetaJSON]` is just one of many plugins that consume that data).

Unfortunately, I wasn't able to do that because then my plugin that creates the cpanfile also doesn't get these dependencies. And MetaJSON runs add_file() in the gather files phase, which makes it tricky to create the cpanfile, then remove the dependencies before the META.json file is created.

> But I should caution you that "they of no use to the end user" is not necessarily true

I can't imagine a good reason where someone would need an author or release test but doesn't want to clone the git repository. (But I agree that most distributions don't agree with me. :) )

**Comment by karenetheridge** [comment]
The META.json file is a ::FromCode object - its content is not populated until the very end of the build -- which has to be this way because prereqs aren't known until very late in the build process. Absolutely no prereqs are known at filegathering time.

I would suggest you create a separate cpanfile to contain your extra prereqs, which is maintained entirely separately outside of Dist::Zilla, and is never added to the build to begin with.

And not everyone uses git -- many people still submit patches directly against the shipped distribution and send the patch via email or via rt.cpan.org :)

**Comment by skirmess** [comment]
Thanks for your feedback, Karen. That request was indeed the wrong way.

I've written a small PrereqSource plugin that moves the develop prereqs to a stash. My plugin that creates the cpanfile can then get them from the stash.
