### ISSUE TITLE
Is there a way to specify a particular version of a plugin?

### ISSUE THREAD

**Issue by hartzell** [rjbs/Dist-Zilla#618]
Is there a way specify a plugin in a `dist.ini` file that ensures that `dzil authordeps` uses a particular version (or at least a version >= X)?

**Comment by karenetheridge** [comment]
; authordep Foo::Bar = 1.23

**Comment by hartzell** [comment]
That doesn't seem to do it:

```
(alice)[19:57:52]moox-strictconstructor>>git diff dist.ini
diff --git a/dist.ini b/dist.ini
index 9b23923..2e7e61f 100644
--- a/dist.ini
+++ b/dist.ini
@@ -14,3 +14,6 @@ Test::CPAN::Meta = 0
 Test::Pod::Coverage = 0
 Pod::Coverage::TrustPod = 0
 Test::Pod = 0
+
+; authordep Dist::Zilla::PluginBundle::HARTZELL = 0.011
+;
(alice)[19:58:10]moox-strictconstructor>>dzil authordeps
Dist::Zilla::PluginBundle::HARTZELL
Dist::Zilla::Plugin::Prereqs
Software::License::Perl_5
(alice)[19:58:13]moox-strictconstructor>>
```

Here's the bit of `Dist::Zilla::Util::AuthorDeps.pm` that's parsing it, and a bit of screwing around with the regex on line 80 convinced me that the line above is matching.

```perl
 78   while (<$fh>) {
 79     chomp;
 80     next unless /\A\s*;\s*authordep\s*(\S+)\s*(?:=\s*([^;]+))?\s*/;
 81     my $module = $1;
 82     my $ver = $2 // "0";
 83     $ver =~ s/\s+$//;
 84     # Any "; authordep " is inserted at the beginning of the list
 85     # in the file order so the user can control the order of at least a part of
 86     # the plugin list
 87     push @packages, $module;
 88     # And added to the requirements so we can use it later
 89     $reqs->add_string_requirement($module => $ver);
 90   }
```

Is the `authordeps` subcommand not supposed to return the version?

**Comment by karenetheridge** [comment]
did you look at `dzil authordeps --help`?

**Comment by hartzell** [comment]
I hadn't.  I now see that `authordeps --versions` causes it to output the version.  That is, in fact, the answer to the question that I started off with.  But it doesn't quite get me where I want to go.  

```
(alice)[11:03:34]moox-strictconstructor>>dzil authordeps  --versions
Dist::Zilla::PluginBundle::HARTZELL = 0.011
Dist::Zilla::Plugin::Prereqs = 0
Software::License::Perl_5 = 0
(alice)[11:03:51]moox-strictconstructor>>dzil authordeps  --versions | cpanm -L /tmp/blort
--> Working on Dist::Zilla::PluginBundle::HARTZELL
Fetching http://www.cpan.org/authors/id/H/HA/HARTZELL/Dist-Zilla-PluginBundle-HARTZELL-0.010.tar.gz ... OK
Configuring Dist-Zilla-PluginBundle-HARTZELL-0.010 ... OK
```

My goal is to write up instructions (similar to the CONTRIBUTING doc in e.g. `Dist::Zilla::Plugin::Test::PodSpelling`) and be reasonably certain that the resulting setup actually works.

Given that I've fixed deficiencies in e.g. the `@HARTZELL` bundle, I'd like to give instructions which are sure to work.   `cpanm` doesn't do the right thing with `dzil's` output.   This (swapping `dzil's` " = " for the CPAN Meta Spec's "~" works (e.g. specifying a non-existent future version to test):

```
(alice)[11:11:08]moox-strictconstructor>>dzil authordeps  --versions | sed -e 's/ = /~/' | cpanm -L /tmp/blort
Found Dist::Zilla::PluginBundle::HARTZELL 0.010 which doesn't satisfy 0.011.
```

I might do just as well by putting a warning in the README,  nearly anyone who's installing prereqs from scratch is going to get the latest anyway (unless they're pulling from a vendor'ed DPAN), so...

Thanks for the help!

**Comment by karenetheridge** [comment]
I think you can get what you need with `dzil authordeps --missing | cpanm; dzil listdeps --missing | cpanm`, or possibly make use of the `dzil stale` command.
