### ISSUE TITLE
Where does AutoPrereqs extract its output to?

### ISSUE THREAD

**Issue by lsiden** [rjbs/Dist-Zilla#641]
I cannot tell from the documentation where AutoPrereqs extracts its output to.  I cannot tell that it generates any file.  Removing it from my dist.ini does not appear to affect my build.  What affect does AutoPrereqs have on a build?

**Comment by karenetheridge** [comment]
You'll see the prerequisites show up in `META.yaml` and `META.json`.  Make sure that you are using the `[MetaYAML]` and `[MetaJSON]` plugins.

If you're using the `[CPANFile]` plugin, you'll also see prerequisites generated into `cpanfile`.
