### ISSUE TITLE
Dist::Zilla::Plugin::PodSyntaxTests - author-pod-syntax.t - Can't locate Test::Pod

### ISSUE THREAD

**Issue by srchulo** [rjbs/Dist-Zilla#644]
For perl 5.10-5.18, I'm seeing this error when running `author-pod-syntax.t`:

```
t/author-pod-syntax.t ....... Can't locate Test/Pod.pm in @INC (you may need to install the Test::Pod module)
```

Even though the test should never get to the `use Test::POD` line since it's not author testing.

Here is an example of these failures:

https://travis-ci.com/srchulo/Mojolicious-Plugin-BcryptSecure/builds/132719188

**Comment by karenetheridge** [comment]
> since it's not author testing

Yes it is -- I see AUTHOR_TESTING is set to 1 in the environment.  You should add Test::Pod to your develop prereqs -- and then the travis-perl helpers will take care of the rest.

**Comment by srchulo** [comment]
ah, my mistake. Thank you for pointing that out!
