### ISSUE TITLE
Abstract extraction cannot handle escapes

### ISSUE THREAD

**Issue by davel** [rjbs/Dist-Zilla#646]
Dist::Zilla doesn't decode escaped characters when it extracts the abstract from POD. The escape sequences end up in META.*.

For example,
```
=head1 NAME

Smiling::Cat::With::Heart::Shaped::Eyes - Looks like E<128571>

=cut
```
yields `abstract: ' Looks like E<128571>'` rather than `abstract: 'Looks like 😻'`.

**Comment by karenetheridge** [comment]
By any chance have you noticed a published distribution on cpan where this problem can be observed?

**Comment by davel** [comment]
> By any chance have you noticed a published distribution on cpan where this problem can be observed?

Not AFAIK. In this one I corrected the abstract in dist.ini; https://metacpan.org/release/DLAMBLEY/App-RetroPAN-0.01
