### ISSUE TITLE
Redundant dependency on Class::Load

### ISSUE THREAD

**Issue by kentfredric** [rjbs/Dist-Zilla#659]
As per the changes entry in https://github.com/rjbs/Dist-Zilla/commit/ff42620c2f0badbbb2e5042e5b5662286030239a  / https://github.com/rjbs/Dist-Zilla/pull/598

There should be no more dependency on Class::Load

However:

https://metacpan.org/source/RJBS/Dist-Zilla-6.015/META.json#L54

And this looks due to 

https://github.com/rjbs/Dist-Zilla/blob/64dd98f9639427d89956ea547f33dca0ef2efe10/dist.ini#L40

**Comment by rjbs** [comment]
This has been addressed.
