### ISSUE TITLE
Dist::Zilla pod broken "Chrome" link (404 error)

### ISSUE THREAD

**Issue by rafork** [rjbs/Dist-Zilla#663]
The Dist::Zilla pod's ATTRIBUTES / logger section contains a "Chrome" link to https://metacpan.org/pod/Dist::Zilla::Chrome which returns a 404 error. Dist::Zilla::Chrome isn't a module. There is Dist::Zilla::Chrome::Term and Dist::Zilla::Chrome::Test, but no Dist::Zilla::Chrome.

Perhaps it should be a link to Dist::Zilla::Chrome::Term.

Perhaps it should be a link to Dist::Zilla::Role::Chrome (my vote).

Perhaps it shouldn't be a link at all.

If you'd like a pull request, let me know what it should change to.

**Comment by rjbs** [comment]
Your vote sounds good to me.

**Comment by rafork** [comment]
Thanks. I've created a pull request (#664).

**Comment by rjbs** [comment]
This was merged.
