### ISSUE TITLE
Invalid attribute name r250g60b127

### ISSUE THREAD

**Issue by robrwo** [rjbs/Dist-Zilla#667]
I've upgraded to 6.019 from 6.015 on Perl 5.28.1 and now get the following error running any command:
> Invalid attribute name r250g60b127 at [deleted]/perl5/perlbrew/perls/perl-5.28.1/lib/site_perl/5.28.1/Dist/Zilla/Chrome/Term.pm line 91.

Downgrading back to 6.015 fixes this issue.

**Comment by rjbs** [comment]
Nice.  I know roughly the problem and will sort it out.

**Comment by rjbs** [comment]
@robrwo So, this is (probably) happening because you have the $COLORTERM env var set to `truecolor` but your terminal doesn't support it.  Could you have a look at how you're letting that get set, just to see if you think this is an error at your side?

**Comment by rjbs** [comment]
…and last thing, @robrwo , try building dzil from the master branch on this repo?

**Comment by robrwo** [comment]
I didn't get a chance to try the build from the repo. But the latest release 6.020 seems to work fine.

**Comment by rjbs** [comment]
@robrwo Great!  Same bug got reported by a coworker so we were able to investigate it very quickly.
