### ISSUE TITLE
AutoPrereq + "use feature 'foo'" adds feature.pm as a dependency [rt.cpan.org #81309]

### ISSUE THREAD

**Issue by rjbs** [rjbs/Dist-Zilla#693]
https://rt.cpan.org/Ticket/Display.html?id=81309

**Comment by karenetheridge** [comment]
Not a bug, and this ticket was rejected in 2013.

**Comment by karenetheridge** [comment]
also reference https://rt.cpan.org/Ticket/Display.html?id=78151

still not a bug, but something clever could use the feature list to figure out the implied minimum perl version.

**Comment by rjbs** [comment]
I agree, this isn't a bug.  If it only requires version 0, it only effectively requires that the library be installed.  I think we do the same for warnings?  Without some harm being caused, I think this should be closed.
