### ISSUE TITLE
Broken dependency specification

### ISSUE THREAD

**Issue by christopherraa** [rjbs/Dist-Zilla#699]
In the commit acae2ee4a76092a08582b2e89ac09393dc9abaf3 you start depending on `Software::License 0.104001`. That version has however never been released, according to [Software::License on Metacpan](https://metacpan.org/pod/Software::License).

**Comment by christopherraa** [comment]
Oh, and why this is a problem: Installing `Dist::Zilla` now fails. DIscovered this as our nightly builds started failing due to them trying to install the newest version of `Dist::Zilla`.

**Comment by awalrond** [comment]
Just a plus one. With latest tagged release, cpanm now bails on Dist-Zilla with

! Installing the dependencies failed: Installed version (0.103014) of Software::License is not in range '0.104001'
! Bailing out the installation for Dist-Zilla-6.024.

I see Software::license 1.104001 has been tagged in the repo, but not sure what the mechanics are of this reaching CPAN?

**Comment by ferki** [comment]
@christopherraa: thanks for reporting it! I saw the same build errors briefly in the morning, but didn't have time to take action immediately.

When I came back to it now, I was glad to see it was already reported, and even [solved, apparently](https://metacpan.org/release/RJBS/Software-License-0.104001) (thanks, @rjbs)!

**Comment by christopherraa** [comment]
@ferki ! Long time no see (TPC@Glasgow). Hope you are doing well.

And yes, I can confirm that everything seems to be working great now, so I am closing this issue.  Thanks @rjbs !

**Comment by rjbs** [comment]
(Yeah, sorry about this!  I thought I'd made a release, but my release process choked because of some boring git stuff.)

**Comment by doomvox** [comment]
Just thought I'd mention I'm still tripping over this bug years later.  It's nice that it's been fixed, but I don't seem to be able to do an upgrade to get past the breakage, so it's going to take some manual intervention for me to fix this system (possibly just blowing a lot of things away so I can install from scratch).

Thanks for the bug report, it's nice to know I'm not crazy.

**Comment by karenetheridge** [comment]
> but I don't seem to be able to do an upgrade to get past the breakage

@doomvox can you describe your problem in more detail please?
