### ISSUE TITLE
CPANFile Plugin Creating Two cpanfiles

### ISSUE THREAD

**Issue by theory** [rjbs/Dist-Zilla#700]
Looks like a recent-ish change to Dist::Zilla causes some plugin to create a cpanfile even if the CPANFile plugin isn't enabled. Noticed with this config:

``` ini
[CPANFile]
filename = dist/cpanfile
```

Used to just create `dist/cpanfile`, but now I see there is also a `cpanfile`. If I remove the `filename` line, I get an error:

```
[DZ] attempt to add cpanfile multiple times; added by: filename set by GatherDir (Dist::Zilla::Plugin::GatherDir line 226); encoded_content added by GatherDir (Dist::Zilla::Plugin::GatherDir line 227); text from coderef added by CPANFile (Dist::Zilla::Plugin::CPANFile line 113)
aborting; duplicate files would be produced at lib/perl5/site_perl/5.30.2/Dist/Zilla/App/Command/build.pm line 107.
```

Does GatherDir now always create a cpanfile?

**Comment by Grinnz** [comment]
No, but it will gather one if it exists in the directory and is not excluded.

**Comment by theory** [comment]
I'm an idiot. It is not generating the root cpanfile, I just happened to have a copy of it in my working directory, not committed or anything. 🤦🏻  Sorry for the noise.
