### ISSUE TITLE
Feature request: support getting PAUSE credentials from environment variables

### ISSUE THREAD

**Issue by skaji** [rjbs/Dist-Zilla#720]
I'm using 1password, and I store my PAUSE credentials in it.

If UploadToCPAN plugin supports getting PAUSE credentials from environment variables,
then I don't need to store PAUSE credentials in `~/.pause` anymore and I can release CPAN modules by: 

```console
❯ export PAUSE_USERNAME=op://Personal/pause/username
❯ export PAUSE_PASSWORD=op://Personal/pause/password

# "op" is a CLI of 1password,
# which runs "dzil release" with PAUSE_USERNAME/PAUSE_PASSWORD references
# replaced with their corresponding secret value.
❯ op run -- dzil release
```

See also:
* I tried to modify UploadToCPAN in
https://github.com/skaji/Dist-Zilla-Plugin-UploadToCPAN-CredentialsFromEnv/blob/main/lib/Dist/Zilla/Plugin/UploadToCPAN/CredentialsFromEnv.pm
and the change should be small.
* https://developer.1password.com/docs/cli/secret-references

**Comment by gflohr** [comment]
+1
