### ISSUE TITLE
feature request - make the PodCoverageTests plugin compatible with the experimental class feature

### ISSUE THREAD

**Issue by lschierer** [rjbs/Dist-Zilla#726]
the experimental class feature auto generates methods based on my attributes, as well as auto generating a new() method for me.  Even if I have an =attr section for each attribute,  the PodCoverageTests detects the lack of a corresponding =method section for any attribute that has a :reader modifier as well as the missing =method section for the constructor.  

As Dist::Zilla and Pod::Weaver seem to aim at helping me reduce repetitive steps in the development process and focus on the meaningful parts, working with this new feature seems like a natural win for everyone.   I'd like to have a single section per attribute that covers its existence both as an attribute of the class, as well as the auto generated getter and (if appropriate) setter for that attribute.  PodCoverageTests shouldn't need me to write 2 to 3 sections for the attribute. 

Thanks!

**Comment by Grinnz** [comment]
Since this simply writes a test file using Test::Pod::Coverage, that is probably the right place to add this feature.

**Comment by lschierer** [comment]
Thanks, willdo.

**Comment by lschierer** [comment]
https://rt.cpan.org/Ticket/Display.html?id=154671
